(add-to-list 'load-path "~/.emacs.d/dot-emacs/src/")
(add-to-list 'load-path "~/.emacs.d/dot-emacs/configs/")

(load "config-m-x")
(load "config-global-keys")
(load "config-general-settings")
(load "config-theme")
(load "config-fonts")
(load "config-initial-buffer")
(load "config-eshell")
(load "config-ranger")
